# Generated by Django 5.0.4 on 2024-07-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_order_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='storeid',
            field=models.CharField(default='default_value', max_length=50),
        ),
    ]
