# Generated by Django 5.0.4 on 2024-08-18 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_order_paymentmethod_order_paymentresult_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='storeid',
        ),
    ]
